"""
Digital-twin engine for industrial power-system assets.

The model keeps a single source of truth — each asset's ``health`` (0-100),
its true latent condition — and derives everything observable from it:

    ground-truth health  ->  physical sensor readings  ->  estimated health

1. **Degradation** lowers ground-truth health each tick (wear + any active
   failure mode).
2. **Telemetry** (temperature, vibration, bearing wear, oil pressure, power
   factor, voltage, current) is generated by interpolating between healthy and
   failed *sensor anchor points*, plus load, failure signatures, and noise.
3. **Health estimation** runs the inverse mapping — a weighted sensor-fusion
   estimate of health from the telemetry alone (what a real predictive model
   would see), smoothed with an EMA. A **Remaining Useful Life (RUL)** estimate
   in hours is projected from the current degradation trajectory.

This separation is deliberate: a digital twin knows the latent state, while the
predictive layer must *infer* it from sensors. It also makes the physics
testable — see ``tests/test_power_system.py``.

NOTE: All values are simulated. This is a demonstration model, not a validated
engineering simulation of real transformers/motors.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum

import numpy as np


class AssetType(Enum):
    """Types of power-system assets."""

    TRANSFORMER = "transformer"
    MOTOR = "motor"
    GENERATOR = "generator"
    PUMP = "pump"


class AssetOperationalState(Enum):
    """Operational states for assets."""

    NORMAL = "normal"
    DEGRADED = "degraded"
    CRITICAL = "critical"
    FAILED = "failed"
    UNDER_MAINTENANCE = "under_maintenance"


# ---------------------------------------------------------------------------
# Failure modes
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FailureSignature:
    """How a developing fault biases sensors and accelerates degradation.

    A failure mode applies a one-off ``health_impact`` when injected and then
    persistently biases the named sensors and multiplies the wear rate until
    the asset is maintained.
    """

    label: str
    health_impact: float  # immediate one-off health loss (percent)
    degradation_multiplier: float  # ongoing wear-rate multiplier
    temp_bias: float = 0.0  # +C
    vibration_bias: float = 0.0  # +mm/s
    bearing_bias: float = 0.0  # +percentage points
    oil_bias: float = 0.0  # +bar (usually negative)
    power_factor_bias: float = 0.0
    current_bias: float = 0.0  # fractional, e.g. 0.2 = +20% current


FAILURE_SIGNATURES: dict[str, FailureSignature] = {
    "bearing_wear": FailureSignature(
        label="Bearing wear",
        health_impact=12.0,
        degradation_multiplier=2.5,
        temp_bias=8.0,
        vibration_bias=4.0,
        bearing_bias=25.0,
    ),
    "insulation_breakdown": FailureSignature(
        label="Insulation breakdown",
        health_impact=16.0,
        degradation_multiplier=2.2,
        temp_bias=12.0,
        power_factor_bias=-0.08,
    ),
    "oil_degradation": FailureSignature(
        label="Oil degradation",
        health_impact=10.0,
        degradation_multiplier=1.8,
        temp_bias=6.0,
        oil_bias=-1.6,
    ),
    "misalignment": FailureSignature(
        label="Shaft misalignment",
        health_impact=8.0,
        degradation_multiplier=1.7,
        temp_bias=3.0,
        vibration_bias=3.5,
    ),
    "overload": FailureSignature(
        label="Sustained overload",
        health_impact=14.0,
        degradation_multiplier=2.3,
        temp_bias=15.0,
        power_factor_bias=-0.05,
        current_bias=0.25,
    ),
}


# ---------------------------------------------------------------------------
# Sensor / asset configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SensorProfile:
    """Physical anchor points mapping health to sensor readings.

    Each sensor is defined at the healthy extreme (health=100) and the failed
    extreme (health=0); telemetry is interpolated between them.
    """

    nominal_temp: float
    failure_temp: float
    nominal_vibration: float
    failure_vibration: float
    nominal_oil_pressure: float
    failure_oil_pressure: float
    nominal_power_factor: float
    failure_power_factor: float
    nominal_voltage: float
    nominal_current: float
    temp_noise: float = 1.2
    vibration_noise: float = 0.15


@dataclass(frozen=True)
class AssetConfig:
    """Static configuration for a single asset."""

    asset_id: str
    asset_type: AssetType
    name: str
    rated_capacity: float  # kVA or kW
    sensors: SensorProfile
    normal_temp_range: tuple[float, float]
    normal_vibration_range: tuple[float, float]
    degradation_rate: float  # base health loss per tick (percent)
    critical_threshold: float
    failure_threshold: float
    typical_load: float = 0.7  # fraction of rated capacity in steady state


@dataclass
class TelemetryData:
    """A single set of sensor readings for an asset at one tick."""

    timestamp: datetime
    temperature: float  # Celsius
    vibration: float  # mm/s RMS
    voltage: float  # Volts
    current: float  # Amps
    bearing_wear: float  # 0-100 %
    oil_pressure: float  # bar
    health_score: float  # 0-100 %, sensor-estimated health (displayed)
    power_factor: float  # 0-1
    rul_hours: float  # estimated remaining useful life (hours)
    anomaly_score: float  # 0-100, higher = more anomalous
    load: float  # % of rated capacity
    efficiency: float  # 0-1

    def to_dict(self) -> dict:
        """Serialise telemetry for JSON transport."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "temperature": round(float(self.temperature), 2),
            "vibration": round(float(self.vibration), 3),
            "voltage": round(float(self.voltage), 1),
            "current": round(float(self.current), 1),
            "bearing_wear": round(float(self.bearing_wear), 2),
            "oil_pressure": round(float(self.oil_pressure), 2),
            "health_score": round(float(self.health_score), 1),
            "power_factor": round(float(self.power_factor), 3),
            "rul_hours": round(float(self.rul_hours), 1),
            "anomaly_score": round(float(self.anomaly_score), 1),
            "load": round(float(self.load), 1),
            "efficiency": round(float(self.efficiency), 3),
        }


@dataclass
class AssetData:
    """Complete runtime state of a single asset.

    ``true_health`` is the latent ground-truth condition that drives the physics
    and is never directly observable in the real world. ``estimated_health`` is
    the EMA-smoothed sensor-fusion estimate — the value the product actually
    displays and reasons about, exactly as a real condition-monitoring system
    only ever *infers* condition from sensors.
    """

    config: AssetConfig
    true_health: float = 100.0  # latent ground truth (physics driver)
    estimated_health: float = 100.0  # observed estimate (displayed / reasoned on)
    operating_state: AssetOperationalState = AssetOperationalState.NORMAL
    total_operating_hours: float = 0.0
    last_maintenance: datetime | None = None
    failure_mode: str | None = None

    @property
    def health(self) -> float:
        """Backward-compatible alias for the observed (estimated) health."""
        return self.estimated_health

    def to_dict(self) -> dict:
        """Serialise asset state for JSON transport.

        ``health`` is the observed (sensor-estimated) value shown to users;
        ``true_health`` is exposed only for transparency/debugging and is clearly
        labelled as the simulator's latent ground truth.
        """
        return {
            "asset_id": self.config.asset_id,
            "asset_type": self.config.asset_type.value,
            "name": self.config.name,
            "health": round(self.estimated_health, 1),
            "true_health": round(self.true_health, 2),
            "operating_state": self.operating_state.value,
            "total_operating_hours": round(self.total_operating_hours, 2),
            "last_maintenance": self.last_maintenance.isoformat()
            if self.last_maintenance
            else None,
            "failure_mode": self.failure_mode,
            "failure_label": FAILURE_SIGNATURES[self.failure_mode].label
            if self.failure_mode in FAILURE_SIGNATURES
            else None,
        }


def _lerp(healthy: float, failed: float, stress: float) -> float:
    """Interpolate a sensor value given a stress fraction (0 healthy, 1 failed)."""
    return healthy + (failed - healthy) * stress


class PowerSystem:
    """Digital twin of an industrial power system with four assets."""

    # Each tick represents this many simulated minutes of operation. Chosen so
    # that Remaining-Useful-Life estimates read as realistic industrial horizons
    # (hundreds of hours) while the demo advances every couple of wall seconds.
    SIMULATED_MINUTES_PER_TICK: float = 15.0
    # Backwards-compatible alias (seconds of simulated time per tick).
    TICK_DURATION_SECONDS: float = SIMULATED_MINUTES_PER_TICK * 60.0

    # EMA smoothing factor for the health estimate (higher = more responsive).
    _HEALTH_ESTIMATE_ALPHA: float = 0.35

    def __init__(self, seed: int | None = None):
        """Initialise the digital twin.

        Args:
            seed: RNG seed for reproducible simulations.
        """
        self.rng = np.random.default_rng(seed)
        self.tick_count: int = 0
        self.start_time: datetime = datetime.now()
        self.assets: dict[str, AssetData] = {}
        self.telemetry_history: dict[str, list[TelemetryData]] = {}
        self._history_limit = 120
        self._initialize_assets()

    # -- setup ------------------------------------------------------------

    def _initialize_assets(self) -> None:
        """Create the initial fleet."""
        asset_configs = [
            AssetConfig(
                asset_id="T1",
                asset_type=AssetType.TRANSFORMER,
                name="Traction Transformer",
                rated_capacity=1000.0,
                sensors=SensorProfile(
                    nominal_temp=58.0,
                    failure_temp=115.0,
                    nominal_vibration=0.8,
                    failure_vibration=6.0,
                    nominal_oil_pressure=5.5,
                    failure_oil_pressure=1.8,
                    nominal_power_factor=0.97,
                    failure_power_factor=0.80,
                    nominal_voltage=25000.0,
                    nominal_current=40.0,
                    temp_noise=1.0,
                    vibration_noise=0.12,
                ),
                normal_temp_range=(40.0, 75.0),
                normal_vibration_range=(0.5, 2.0),
                degradation_rate=0.020,
                critical_threshold=40.0,
                failure_threshold=12.0,
                typical_load=0.72,
            ),
            AssetConfig(
                asset_id="M1",
                asset_type=AssetType.MOTOR,
                name="Traction Motor",
                rated_capacity=500.0,
                sensors=SensorProfile(
                    nominal_temp=62.0,
                    failure_temp=120.0,
                    nominal_vibration=1.6,
                    failure_vibration=9.0,
                    nominal_oil_pressure=4.5,
                    failure_oil_pressure=1.2,
                    nominal_power_factor=0.90,
                    failure_power_factor=0.72,
                    nominal_voltage=1500.0,
                    nominal_current=215.0,
                    temp_noise=1.4,
                    vibration_noise=0.22,
                ),
                normal_temp_range=(50.0, 85.0),
                normal_vibration_range=(1.0, 3.5),
                degradation_rate=0.032,
                critical_threshold=35.0,
                failure_threshold=8.0,
                typical_load=0.78,
            ),
            AssetConfig(
                asset_id="G1",
                asset_type=AssetType.GENERATOR,
                name="Signalling Backup Generator",
                rated_capacity=750.0,
                sensors=SensorProfile(
                    nominal_temp=60.0,
                    failure_temp=118.0,
                    nominal_vibration=1.2,
                    failure_vibration=7.5,
                    nominal_oil_pressure=5.0,
                    failure_oil_pressure=1.5,
                    nominal_power_factor=0.92,
                    failure_power_factor=0.75,
                    nominal_voltage=400.0,
                    nominal_current=1082.0,
                    temp_noise=1.3,
                    vibration_noise=0.18,
                ),
                normal_temp_range=(45.0, 80.0),
                normal_vibration_range=(0.8, 2.5),
                degradation_rate=0.026,
                critical_threshold=38.0,
                failure_threshold=10.0,
                typical_load=0.55,
            ),
            AssetConfig(
                asset_id="P1",
                asset_type=AssetType.PUMP,
                name="Transformer Cooling Pump",
                rated_capacity=50.0,
                sensors=SensorProfile(
                    nominal_temp=45.0,
                    failure_temp=95.0,
                    nominal_vibration=2.0,
                    failure_vibration=10.0,
                    nominal_oil_pressure=4.0,
                    failure_oil_pressure=1.0,
                    nominal_power_factor=0.88,
                    failure_power_factor=0.70,
                    nominal_voltage=415.0,
                    nominal_current=85.0,
                    temp_noise=1.6,
                    vibration_noise=0.28,
                ),
                normal_temp_range=(35.0, 65.0),
                normal_vibration_range=(1.5, 4.0),
                degradation_rate=0.040,
                critical_threshold=30.0,
                failure_threshold=6.0,
                typical_load=0.82,
            ),
        ]

        for config in asset_configs:
            self.assets[config.asset_id] = AssetData(config=config)
            self.telemetry_history[config.asset_id] = []

    # -- accessors --------------------------------------------------------

    def get_asset(self, asset_id: str) -> AssetData | None:
        """Return a specific asset, or None."""
        return self.assets.get(asset_id)

    def get_all_assets(self) -> list[AssetData]:
        """Return all assets."""
        return list(self.assets.values())

    def get_telemetry_history(self, asset_id: str, max_points: int = 100) -> list[TelemetryData]:
        """Return recent telemetry history for an asset (most recent last)."""
        history = self.telemetry_history.get(asset_id, [])
        return history[-max_points:]

    # -- interventions ----------------------------------------------------

    def inject_failure(self, asset_id: str, failure_type: str) -> bool:
        """Inject a developing fault into an asset.

        Applies an immediate health penalty and activates a persistent failure
        signature that biases sensors and accelerates wear until maintenance.

        Args:
            asset_id: Target asset.
            failure_type: One of ``FAILURE_SIGNATURES``.

        Returns:
            True if the failure was injected.
        """
        asset = self.assets.get(asset_id)
        if asset is None or failure_type not in FAILURE_SIGNATURES:
            return False

        signature = FAILURE_SIGNATURES[failure_type]
        asset.true_health = max(0.0, asset.true_health - signature.health_impact)
        asset.failure_mode = failure_type
        # The fault develops over subsequent ticks as sensors ramp; state will
        # follow the estimated health on the next tick.
        self._update_operating_state(asset)
        return True

    def perform_maintenance(self, asset_id: str) -> bool:
        """Restore an asset's health and clear any active fault.

        Args:
            asset_id: Target asset.

        Returns:
            True if maintenance was performed.
        """
        asset = self.assets.get(asset_id)
        if asset is None:
            return False

        if asset.operating_state == AssetOperationalState.FAILED:
            asset.true_health = 75.0  # rebuild after failure — partial restoration
        else:
            asset.true_health = min(100.0, asset.true_health + 45.0)

        asset.failure_mode = None
        asset.last_maintenance = datetime.now()
        # Fault cleared: sensors now read healthy, so snap the estimate up to the
        # restored condition rather than waiting for the EMA to catch up.
        asset.estimated_health = asset.true_health
        self._update_operating_state(asset)
        return True

    def set_under_maintenance(self, asset_id: str, active: bool) -> bool:
        """Flag/unflag an asset as physically under maintenance (paused wear)."""
        asset = self.assets.get(asset_id)
        if asset is None:
            return False
        if active:
            asset.operating_state = AssetOperationalState.UNDER_MAINTENANCE
        else:
            self._update_operating_state(asset)
        return True

    def _update_operating_state(self, asset: AssetData) -> None:
        """Derive operating state from the *observed* (estimated) health.

        Using the sensor estimate — not the latent truth — keeps the status
        badge, health bar, RUL, and agent reasoning mutually consistent: they all
        reflect what the monitoring system can actually see.
        """
        cfg = asset.config
        observed = asset.estimated_health
        if observed <= cfg.failure_threshold:
            asset.operating_state = AssetOperationalState.FAILED
        elif observed <= cfg.critical_threshold:
            asset.operating_state = AssetOperationalState.CRITICAL
        elif observed <= 60.0:
            asset.operating_state = AssetOperationalState.DEGRADED
        else:
            asset.operating_state = AssetOperationalState.NORMAL

    # -- simulation -------------------------------------------------------

    def tick(self) -> dict[str, TelemetryData]:
        """Advance the simulation by one tick.

        Returns:
            Mapping of asset id -> new telemetry reading.
        """
        self.tick_count += 1
        telemetry: dict[str, TelemetryData] = {}

        for asset_id, asset in self.assets.items():
            under_maintenance = asset.operating_state == AssetOperationalState.UNDER_MAINTENANCE
            if not under_maintenance:
                self._degrade(asset)

            reading = self._generate_telemetry(asset)
            telemetry[asset_id] = reading

            # State follows the freshly-estimated health (unless paused for a
            # physical maintenance intervention).
            if not under_maintenance:
                self._update_operating_state(asset)

            history = self.telemetry_history[asset_id]
            history.append(reading)
            if len(history) > self._history_limit:
                history.pop(0)

        return telemetry

    def _effective_degradation_rate(self, asset: AssetData) -> float:
        """Expected health loss per tick, including any active failure mode."""
        rate = asset.config.degradation_rate
        if asset.failure_mode in FAILURE_SIGNATURES:
            rate *= FAILURE_SIGNATURES[asset.failure_mode].degradation_multiplier
        return rate

    def _degrade(self, asset: AssetData) -> None:
        """Apply one tick of wear to latent ground-truth health."""
        # Load varies slightly around the asset's typical load; heavier load
        # wears faster.
        load_factor = 1.0 + float(self.rng.uniform(0.0, 0.10))
        loss = self._effective_degradation_rate(asset) * load_factor
        asset.true_health = max(0.0, asset.true_health - loss)
        asset.total_operating_hours += self.TICK_DURATION_SECONDS / 3600.0

    def _generate_telemetry(self, asset: AssetData) -> TelemetryData:
        """Generate sensor readings from ground-truth health + load + noise."""
        cfg = asset.config
        s = cfg.sensors
        now = datetime.now()

        stress = 1.0 - (asset.true_health / 100.0)  # 0 healthy .. 1 failed
        signature = FAILURE_SIGNATURES.get(asset.failure_mode or "")

        # Instantaneous load fraction (bounded), used for thermal/current terms.
        load_frac = float(np.clip(cfg.typical_load + self.rng.normal(0, 0.06), 0.2, 1.15))
        load_thermal = (load_frac - cfg.typical_load) * 12.0  # +/- C from load swing

        # Rare sensor spikes (transient events).
        spike_temp = 18.0 if self.rng.random() < 0.006 else 0.0
        spike_vib = 2.5 if self.rng.random() < 0.006 else 0.0

        temp_bias = signature.temp_bias if signature else 0.0
        vib_bias = signature.vibration_bias if signature else 0.0
        bearing_bias = signature.bearing_bias if signature else 0.0
        oil_bias = signature.oil_bias if signature else 0.0
        pf_bias = signature.power_factor_bias if signature else 0.0
        current_bias = signature.current_bias if signature else 0.0

        temperature = (
            _lerp(s.nominal_temp, s.failure_temp, stress)
            + load_thermal
            + temp_bias
            + float(self.rng.normal(0, s.temp_noise))
            + spike_temp
        )
        vibration = max(
            0.05,
            _lerp(s.nominal_vibration, s.failure_vibration, stress)
            + vib_bias
            + float(self.rng.normal(0, s.vibration_noise))
            + spike_vib,
        )
        bearing_wear = float(
            np.clip(stress * 80.0 + bearing_bias + self.rng.normal(0, 1.5), 0.0, 100.0)
        )
        oil_pressure = float(
            np.clip(
                _lerp(s.nominal_oil_pressure, s.failure_oil_pressure, stress)
                + oil_bias
                + self.rng.normal(0, 0.12),
                0.2,
                10.0,
            )
        )
        power_factor = float(
            np.clip(
                _lerp(s.nominal_power_factor, s.failure_power_factor, stress)
                + pf_bias
                + self.rng.normal(0, 0.008),
                0.5,
                1.0,
            )
        )
        voltage = s.nominal_voltage * (1.0 + float(self.rng.normal(0, 0.005)))
        current = (
            s.nominal_current
            * load_frac
            * (1.0 + current_bias)
            * (1.0 + float(self.rng.normal(0, 0.02)))
        )

        # Inverse mapping: estimate health from the sensor values (fusion).
        est_health = self._estimate_health(
            cfg, temperature, vibration, bearing_wear, oil_pressure, power_factor
        )
        # EMA smoothing for a stable displayed value.
        asset.estimated_health = (
            self._HEALTH_ESTIMATE_ALPHA * est_health
            + (1.0 - self._HEALTH_ESTIMATE_ALPHA) * asset.estimated_health
        )
        anomaly_score = float(np.clip(100.0 - asset.estimated_health, 0.0, 100.0))
        rul_hours = self._estimate_rul(asset)
        efficiency = float(np.clip(0.96 - stress * 0.22, 0.60, 0.99))

        return TelemetryData(
            timestamp=now,
            temperature=temperature,
            vibration=vibration,
            voltage=voltage,
            current=current,
            bearing_wear=bearing_wear,
            oil_pressure=oil_pressure,
            health_score=asset.estimated_health,
            power_factor=power_factor,
            rul_hours=rul_hours,
            anomaly_score=anomaly_score,
            load=load_frac * 100.0,
            efficiency=efficiency,
        )

    @staticmethod
    def _estimate_health(
        cfg: AssetConfig,
        temperature: float,
        vibration: float,
        bearing_wear: float,
        oil_pressure: float,
        power_factor: float,
    ) -> float:
        """Weighted sensor-fusion estimate of health from telemetry alone.

        Each indicator is normalised to a stress fraction in [0, 1.2] measuring
        how far it sits between its healthy and failed anchors; the weighted mean
        stress is inverted to a 0-100 health estimate.
        """
        s = cfg.sensors

        def stress_of(value: float, healthy: float, failed: float) -> float:
            span = failed - healthy
            if span == 0:
                return 0.0
            return float(np.clip((value - healthy) / span, 0.0, 1.2))

        temp_stress = stress_of(temperature, s.nominal_temp, s.failure_temp)
        vib_stress = stress_of(vibration, s.nominal_vibration, s.failure_vibration)
        bearing_stress = float(np.clip(bearing_wear / 80.0, 0.0, 1.2))
        # Oil & power factor degrade downward, so invert the anchors.
        oil_stress = stress_of(oil_pressure, s.nominal_oil_pressure, s.failure_oil_pressure)
        pf_stress = stress_of(power_factor, s.nominal_power_factor, s.failure_power_factor)

        fused = (
            temp_stress * 0.25
            + vib_stress * 0.30
            + bearing_stress * 0.20
            + oil_stress * 0.10
            + pf_stress * 0.15
        )
        return float(np.clip(100.0 * (1.0 - fused), 0.0, 100.0))

    def _estimate_rul(self, asset: AssetData) -> float:
        """Project remaining useful life (hours) from the current trajectory.

        Uses the smoothed health estimate and the expected per-tick degradation
        rate to extrapolate ticks-to-failure-threshold, then converts to hours.
        """
        rate = self._effective_degradation_rate(asset)
        headroom = asset.estimated_health - asset.config.failure_threshold
        if headroom <= 0:
            return 0.0
        if rate <= 1e-6:
            rate = 1e-6
        rul_ticks = headroom / rate
        return rul_ticks * self.TICK_DURATION_SECONDS / 3600.0

    # -- summary ----------------------------------------------------------

    def get_state_summary(self) -> dict:
        """Return a fleet-level state summary."""
        assets = []
        overall_health = 0.0
        min_rul = float("inf")
        for asset in self.assets.values():
            assets.append(asset.to_dict())
            overall_health += asset.estimated_health  # observed fleet health
            min_rul = min(min_rul, self._estimate_rul(asset))

        n = len(self.assets) or 1
        overall_health /= n
        uptime_hours = self.tick_count * self.TICK_DURATION_SECONDS / 3600.0

        return {
            "tick_count": self.tick_count,
            "uptime_hours": round(uptime_hours, 2),
            "overall_health": round(overall_health, 2),
            "min_rul_hours": round(min_rul, 1) if min_rul != float("inf") else None,
            "assets": assets,
        }
